IF NOT EXISTS (SELECT * FROM sys.change_tracking_databases WHERE database_id = DB_ID(N'C:\USERS\MOHIT\DOCUMENTS\VISUAL STUDIO 2010\PROJECTS\SCHOOL MANAGEMENT SYSTEM\SCHOOL MANAGEMENT SYSTEM\SMS.MDF')) 
   ALTER DATABASE [C:\USERS\MOHIT\DOCUMENTS\VISUAL STUDIO 2010\PROJECTS\SCHOOL MANAGEMENT SYSTEM\SCHOOL MANAGEMENT SYSTEM\SMS.MDF] 
   SET  CHANGE_TRACKING = ON
GO
